# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

WORKDIR /app

# Install system dependencies if needed
RUN apt-get update && apt-get install -y --no-install-recommends gcc libpq-dev && rm -rf /var/lib/apt/lists/*

# Copy the project files
COPY . /app

# Install the package using pip
RUN pip install --no-cache-dir .

# Expose a port if needed (adjust as necessary)
EXPOSE 8000

# Run the MCP server
CMD ["prefect-mcp-server"]
